import {
  Monitor,
  Smartphone,
  Gamepad2,
  Tv,
  Camera,
  Home,
  Menu,
  ChevronRight,
  Headphones,
  Watch,
  Cpu,
  Keyboard,
  Zap,
  ShieldCheck,
  LayoutGrid,
  Speaker,
  Mic2,
  Cloud,
  WashingMachine,
  Flame,
  Router,
  Disc,
  Bell,
  Lightbulb,
  Plug,
  Lock,
  Cctv,
  Video,
  Sun,
  Battery,
  Lamp,
  ToggleRight,
  Activity,
  PhoneCall,
  Share2,
  Wind,
  Rss,
  HardDrive,
  Droplets,
  PlusSquare,
  Box
} from 'lucide-react';

export const DEFAULT_ICON = LayoutGrid;

export const ICON_MAP: Record<string, any> = {
  'laptops': Monitor,
  'tablets': Smartphone,
  'smartphones': Smartphone,
  'audio': Speaker,
  'wearables': Watch,
  'gaming': Gamepad2,
  'smart-home': Zap,
  'tv': Tv,
  'cameras': Camera,
  'hardware': Cpu,
  'accessories': Keyboard,
  'security': ShieldCheck,
  'amazon-alexa': Speaker,
  'google': Cloud,
  'home-appliances': WashingMachine,
  'limited-time-offer': Flame,
  'network-access-points': Router,
  'robot-vacuum': Disc,
  'smart-intercom': Bell,
  'smart-lock-2': Lock,
  'voice-assistant': Mic2,
  'wifi-smart-camera': Cctv,
  'smart-switches': Zap,
  'smart-lighting': Lightbulb,
  'lighting': Lightbulb,
  'smart-lock': Lock,
  'smart-plugs': Plug,
  'audio-gear': Speaker,
  // Detailed mapping for all categories
  'outdoor-wifi-camera-2': Camera,
  'indoor-wifi-camera-2': Camera,
  '4g-security-camera': Video,
  'solar-smart-camera': Sun,
  'battery-wifi-camera': Battery,
  'smart-wall-switches': ToggleRight,
  'sensor': Activity,
  'gateway-bridge': Share2,
  'central-control-panel': Smartphone,
  'smart-motorized-curtain-track': Box,
  'smart-water-level': Droplets,
  'ac-control-smart': Wind,
  'zigbee-smart-products': Rss,
  'nvr': HardDrive,
  // Arabic slugs/names mapping for completeness if needed
  'مفاتيح-ذكية-ذاتية-التركيب': Zap,
  'أمازون-أليكسا': Speaker,
  'جوجل': Cloud,
  'الأجهزة-المنزلية': WashingMachine,
  'عرض-لفترة-محدودة': Flame,
  'الشبكات-ونقاط-الوصول': Router,
  'مكنسة-روبوت': Disc,
  'اجهزة-انتركوم-ذكية': Bell,
  'اقفال-ذكية': Lock,
  'مساعد-صوتي': Mic2,
  'كاميرات-ذكية-لاسلكية': Cctv,
  'إضاءة-ذكية': Lightbulb,
  'مقابس-ذكية': Plug,
  'مفاتيح-الحائط-بتقنية-واي-فاي': Zap,
};
